version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: yarn build
      - store_artifacts:
          path: docs
